version: "3.7"
services:
  # backend:
  #   todo
  #   depends_on:
  #     - db
  db:
    image: mysql:8.0.19
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - 4306:3306
    secrets:
      - db-password
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
  # frontend:
  #   todo
  #   depends_on:
  #     - backend

secrets:
  db-password:
    file: db/password.txt
